### PR TITLE
Added composer file

### PR DESCRIPTION
**Pull request by shoaibali**

### CODE REVIEW

**Comment by aidan-** [comment]
LGTM

I really should have added this a while ago, thanks!

**Comment by shoaibali** [comment]
Thanks a bunch @aidan- 

I assume this is already on packagist?

**Comment by aidan-** [comment]
It is not currently.  It will need someone in charge of the 'simplesamlphp' vendor to add it.  

I'll send an email to one of the SSP mail lists today to work out how it should be done.

**Comment by aidan-** [comment]
@shoaibali the package is now on packagist
https://packagist.org/packages/aidan/simplesamlphp-module-simpletotp

Fyi, the simplesamlphp dev's suggested putting it under a different vendor name, not the simplesamlphp namespace.

**Comment by shoaibali** [comment]
thank you @aidan- for getting it into packagist.

Yes, I realized that is the convention. Hence my recommendation in README.

**Pull request merged**
